Repository AY2425S2-CS2103-F09-2/tp, pull requests merged in 2025-04, with the labels that each got.

#111 Add tests and update UG, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ScheduleSequenceDiagram.puml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/SessionTest.java
Labels: type.Task

#118 Update UG for information changed from AB3
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#122 Update UG (Quick Start) for tags
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#123 Update UG (Command Summary) for tags
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#135 Update user guide with Remind feature
  docs/UserGuide.md
Labels: alpha-bug

#139 feat(modelclassdiagram): add Reminder class to UML diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#136 fix(remindcommandparser): prevent preamble and disallow non-future dates
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
Labels: alpha-bug

#145 Update UG to use EduEase images
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/SampleDataUtilTest.java
Labels: type.Task

#126 Add Switch command
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/address/logic/parser/TagsCommandParser.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Session.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ReminderPanel.java
  src/main/java/seedu/address/ui/SessionPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SwitchCommandParserTest.java
Labels: priority.High, alpha-bug

#148 Update model component for tags
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
Labels: severity.Low, alpha-bug

#159 update Developer Guide for Remind
  docs/DeveloperGuide.md
Labels: type.Task

#158 Fix redo command implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/botosek.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
  src/main/java/seedu/address/model/exceptions/NoPreviousModelStateException.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: alpha-bug

#157 Update tadacheng.md with changes from v1.3 till now
  docs/team/tadacheng.md
Labels: type.Task

#162 Add manual testing for note feature
  docs/DeveloperGuide.md
  docs/team/tadacheng.md
Labels: type.Task

#165 Fix issues for no tags found
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/test/java/seedu/address/logic/commands/TagsCommandTest.java
Labels: severity.Low, alpha-bug

#163 Add instructions for tags testing in dg
  docs/DeveloperGuide.md
Labels: alpha-bug

#166 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/team/botosek.md
Labels: alpha-bug

#172 Standardize appendix
  docs/DeveloperGuide.md
Labels: alpha-bug

#173 Fix format issues
  docs/DeveloperGuide.md
Labels: alpha-bug

#253 Fix more PED bugs
  docs/UserGuide.md
  docs/diagrams/CommandWithConfirmationSequenceDiagram.puml
  docs/images/CommandWithConfirmationSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: severity.Low
