Repository AY2425S2-CS2103-F09-2/tp, pull requests merged in 2025-03, with the labels that each got.

#35 Refactor Person Class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#39 Update GUI display of ListCommand
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/email_icon.png
  src/main/resources/images/phone_icon.png
  src/main/resources/images/telephone_icon.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/WhiteTheme.css
Labels: type.Enhancement

#43 Adding Remind Command
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
Labels: type.Story

#41 Update model components for tags
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Task

#44 Add validation for phone model
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Task

#50 Refactor command alias handling for dynamic resolution
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Enhancement, priority.Medium

#53 Add schedule feature to manage session scheduling
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Session.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#56 Improve remind
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Reminder.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ReminderPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderPanel.fxml
Labels: type.Story

#57 Display all current unique tags
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: priority.High

#60 Update tag to UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#62 Add Schedule command to UG
  docs/UserGuide.md
Labels: priority.Medium

#64 Update AboutUs
  docs/AboutUs.md
Labels: priority.Medium

#65 Fix remind tab
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#67 Branch update gui
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Reminder.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/schedule/Session.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#80 Update note prefix to fit EduEase prefix format
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: severity.VeryLow

#81 Add confirmation alert to prevent accidental command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommandWithConfirmation.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Session.java
  src/main/java/seedu/address/ui/ReminderPanel.java
  src/main/java/seedu/address/ui/SessionPanel.java
  src/main/resources/view/WhiteTheme.css
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#82 Add schedule cancel command, improve session display
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCancelCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/schedule/ScheduleCancelCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/ScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Session.java
  src/main/java/seedu/address/ui/SessionPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#83 Add edit schedule command
  src/main/java/seedu/address/logic/commands/schedule/ScheduleEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/schedule/ScheduleCancelCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/ScheduleEditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.Medium

#85 Filter students based on tags
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TagsCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Story, type.Enhancement

#87 Branch add undo command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/exceptions/NoPreviousModelStateException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.Medium

#91 Add Redo Command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
Labels: priority.Medium

#89 improve-remind
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/ReminderTest.java
Labels: type.Task

#98 Fixing codestyle
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/main/java/seedu/address/logic/parser/TagsCommandParser.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
  src/main/java/seedu/address/model/schedule/Session.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ReminderTest.java
Labels: priority.Low

#103 Enable assertions in gradle
  build.gradle
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/ReminderTest.java
Labels: type.Task

#106 Update UG and DG on CommandWithConfirmation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandWithConfirmationSequenceDiagram.puml
  docs/images/CommandWithConfirmationSequenceDiagram.png
Labels: type.Task
